### ISSUE TITLE
Documentation and master lack monkeypatch code

### ISSUE THREAD

**Issue by truggeri** [joelhawksley/actionview-component-demo#13]
After hearing the [Ruby on Rails 5by5 podcast](https://5by5.tv/rubyonrails/276), I found this demo repo and came here so that I could incorporate actionview-components _without_ using the master branch of Rails. I was expecting to see either,

1) The monkeypatch [code](https://github.com/joelhawksley/actionview-component-demo/blob/35b9063e2c9985a9baf030756aab1378233fa01a/config/initializers/action_view.rb)
and/or
2) Documentation on how to incorporate the monkeypatch approach.

After not being able to find either, I found the [commit](https://github.com/joelhawksley/actionview-component-demo/commit/a937ca42e5b447fe031ed988c0de5a22bd78c430) where you took it out to refer to Rails master. It seems to me that there should be some documentation around this to make it easy for those using this demo app for their Rails 5.2 and below apps.

**Comment by joelhawksley** [comment]
@truggeri whoops! I thought I had pushed the monkey patch, but I hadn't! It's in master now. My apologies ❤️
