### ISSUE TITLE
current_user helper in components?

### ISSUE THREAD

**Issue by rosendi** [joelhawksley/actionview-component-demo#21]
How could I make `current_user` available in all components without passing it each time? `include ApplicationHelper` doesn't work.

P.S. I use Sorcery.

**Comment by skyksandr** [comment]
Current attributes can be a solution. More info here: 
https://api.rubyonrails.org/classes/ActiveSupport/CurrentAttributes.html

**Comment by rosendi** [comment]
@skyksandr thank you, but I'd prefer not to use them.

**Comment by joelhawksley** [comment]
@rosendi currently, we're explicitly passing in the values we need to render our components. I'd be curious to hear what you come up with on your end, though.

**Comment by joelhawksley** [comment]
Closing this issue due to staleness. Feel free to reopen if desired ❤️

**Comment by rosendi** [comment]
I think we should find a way :-) Technically yes - we have to pass all the values (props) we need to render a component, but helpers are more like utilities. In React I would import them and use directly:

```
import projectPath from '....';

const ProjectItem = ({ project }) => (
  <Link to={project_path(project)}>Go to project</Link>
} 
```
Currently if I define a helper in a controller, I have to compute its value and explicitly pass it via attributes. 

Let's say I have a polymorphic controller (real-world example) for comments. Users can comment posts and images.

```
module Post
  class CommentsController < CommentsController
    helper_method :edit_comment_path

    def edit_comment_path(comment, *args)
      edit_post_comment_path(subject, comment, *args)
    end

  private

      def subject
        @subject ||= Post.find(...)
      end
  end
end

module Image
  class CommentsController < CommentsController
    helper_method :edit_comment_path

    def edit_comment_path(comment, *args)
      edit_image_comment_path(subject, comment, *args)
    end

  private

      def subject
        @subject ||= Comment.find(...)
      end
  end
end
```

My comment component should be decoupled from post, image, etc. Currently I do:

```
<%= render Comment, comment: comment, edit_comment_path: edit_comment_path(comment) %>
``` 

but I think this way should work too:

```
<%= render Comment, comment: comment %>
``` 

and the html of the comment component then would be:

```
<%= link_to 'Edit comment', edit_comment_path(comment) %>
```

**Comment by rosendi** [comment]
@ joelhawksley Hello! It's been a while. Do you still pass all helpers explicitly? It sounds like non-rails way to pass all current_*  such as current_user, current_organization, current_project, etc..

**Comment by rosendi** [comment]
ahhh....

<img width="1059" alt="Screenshot 2020-02-16 at 17 47 33" src="https://user-images.githubusercontent.com/803388/74606816-7beb3880-50e4-11ea-924f-8b5ab0d9fbc4.png">

**Comment by joelhawksley** [comment]
@rosendi currently, we do inject the current state explicitly, as doing so enables us to change that state in unit tests. 

You can also use the `helpers.` escape hatch, but it will make your components more difficult to unit test.
