### ISSUE TITLE
Inline templates

### ISSUE THREAD

**Issue by skyksandr** [joelhawksley/actionview-component-demo#4]
First of all - @joelhawksley Thank you! The missing part of Rails I was googling so badly 😄

I have an idea about templates - instead of defining it as a method with heredoc, use the same approach as Sinatra's inline templates can be better
https://github.com/sinatra/sinatra#inline-templates

as, for example, we can define styles in the same place like:

```ruby
class OurComponent
  def hello_message
    "Hello, world!"
  end

  ...
end

__END__

@@template
<div class="title"><%= hello_message %></div>

@@styles
.title {
  font-size: 24px;
}
```

Related code from Sinatra repo [can be found here](https://github.com/sinatra/sinatra/blob/1aa64f9858edc3f93cc8d46e26f724c1ae103b1c/lib/sinatra/base.rb#L1301)

**Comment by joelhawksley** [comment]
@skyksandr this is super interesting!

I'll definitely mention this in the Rails PR, as we are still considering what options would be best for templates in this architecture. 

My gut says that we need something that most editors will be able to syntax-highlight correctly, and will be compatible with different templating engines.

**Comment by tomasc** [comment]
@joelhawksley support for variety of templating languages would be great.

In the meanwhile, I hacked in support for Slim like this:

```ruby
private_class_method def self.compile
      class_eval(
        'def html; ' \
        '@output_buffer = ActionView::OutputBuffer.new; ' +
          # ActionView::Template::Handlers::ERB.erb_implementation.new(template, trim: true).src +
          Slim::RailsTemplate.new.call(OpenStruct.new(identifier: nil), template) +
        '; end'
      )
    end
```

**Comment by joelhawksley** [comment]
Version 1.0.0 of `actionview-component` removes support for inline templates and includes support for the built-in Rails template handlers, including Slim and Haml.

We removed inline templates due to anticipated issues with the type system being developed for Ruby 3. We may revisit them in the future.
